#!/bin/sh

KO_DIRS="drivers/i2c drivers/input/touchscreen drivers/media/usb/gspca drivers/net/usb drivers/net/wireless drivers/pwm drivers/rtc drivers/spi drivers/staging/fbtft drivers/video/backlight fs/efivarfs net/ipv4 net/wireless"

if [ "$1" = "start" ]
then
	KERNELRELEASE=$(uname -r)

	rmmod hynitron_touch
	rmmod spi_gpio
	rmmod spi_bitbang
	rmmod i2c_gpio
	rmmod i2c_algo_bit

	. /etc/profile
	printf "load kernel module: "
	cd /mnt/system/ko/
	for d in $(echo $KO_DIRS) ; do
	    if [ -e /lib/modules/${KERNELRELEASE}/kernel/$d ]; then
		mkdir -p ${KERNELRELEASE}
		for f in $(find /lib/modules/${KERNELRELEASE}/kernel/$d/ -name '*.ko') ; do
			b=$(basename $f)
			[ -e ${KERNELRELEASE}/$b ] || ln -s $f ${KERNELRELEASE}/$b
		done
	    fi
	done
	if [ -e /lib/modules/${KERNELRELEASE}/kernel/drivers/osdrv/interdrv ]; then
		mkdir -p ${KERNELRELEASE}
		for f in $(find /lib/modules/${KERNELRELEASE}/kernel/drivers/osdrv/interdrv/ -name '*.ko') ; do
			b=$(basename $f)
			[ -e ${KERNELRELEASE}/$b ] || ln -s $f ${KERNELRELEASE}/$b
		done
	fi
	if [ -e /lib/modules/${KERNELRELEASE}/kernel/drivers/osdrv/extdrv ]; then
		mkdir -p ${KERNELRELEASE}/3rd
		for f in $(find /lib/modules/${KERNELRELEASE}/kernel/drivers/osdrv/extdrv/ -name '*.ko') ; do
			b=$(basename $f)
			[ -e ${KERNELRELEASE}/3rd/$b ] || ln -s $f ${KERNELRELEASE}/3rd/$b
		done
	fi
	for ko in ${KERNELRELEASE}/*.ko ; do
		if [ -e $ko ]; then
			km=`basename $ko`
			rm -f $km
			ln -s $ko $km
		fi
	done
	mkdir -p 3rd
	for ko in ${KERNELRELEASE}/3rd/*.ko ; do
		if [ -e $ko ]; then
			km=`basename $ko`
			rm -f 3rd/$km
			ln -s ../$ko 3rd/$km
		fi
	done
	ion_size=0
	if [ -e /sys/kernel/debug/ion/cvi_carveout_heap_dump/total_mem ]; then
		ion_size=$(cat /sys/kernel/debug/ion/cvi_carveout_heap_dump/total_mem)
	fi
	insmod soph_sys.ko
	insmod soph_base.ko
	if [ $ion_size != 0 ]; then
		insmod soph_rtos_cmdqu.ko
		insmod soph_fast_image.ko
		insmod soph_mipi_rx.ko
		insmod soph_snsr_i2c.ko
		insmod soph_vi.ko
		insmod soph_vpss.ko
		insmod soph_dwa.ko
		insmod soph_vo.ko
#		insmod soph_mipi_tx.ko
		insmod soph_rgn.ko
	fi
#	insmod soph_wdt.ko
#	insmod soph_clock_cooling.ko
	insmod soph_tpu.ko
	if [ $ion_size != 0 ]; then
		insmod soph_vcodec.ko
		insmod soph_jpeg.ko
		insmod soph_vc_driver.ko MaxVencChnNum=9 MaxVdecChnNum=9
	fi
#	insmod soph_rtc.ko
	if [ $ion_size != 0 ]; then
		insmod soph_ive.ko
	fi
	insmod soph_mon.ko
#	insmod soph_pwm.ko
#	insmod soph_saradc.ko
	insmod soph_wiegand.ko
	echo "OK"
	exit 0
fi
